### ISSUE TITLE
Error: not booted by a multiboot bootloader

### ISSUE THREAD

**Issue by asiawin** [Remco123/CactusOS#4]
When I run CactusOS, it shows the following error message:
![image](https://user-images.githubusercontent.com/52355164/96147480-ff378500-0f24-11eb-991f-45678e6c5b27.png)
QEMU command line arguments; `qemu-system-i386 -cdrom CactusOS.iso -serial stdio -boot d -device VGA,edid=on,xres=1024,yres=768 -usb -device usb-mouse -sdl`

**Comment by Remco123** [comment]
Hello again, this probably has to do with a default optimization by your compiler. The kernel needs to be compiled without optimization otherwise some boot arguments get optimized out. The other reason is that it is way easier to debug code that is not optimized. The user library and applications can be optimized though. Perhaps in the future I will change this for release builds for example. Hope this helps!

**Comment by asiawin** [comment]
> Hello again, this probably has to do with a default optimization by your compiler. The kernel needs to be compiled without optimization otherwise some boot arguments get optimized out. The other reason is that it is way easier to debug code that is not optimized. The user library and applications can be optimized though. Perhaps in the future I will change this for release builds for example. Hope this helps!

I figured out a way to run CactusOS, I commented out the `if` statement which checks the multiboot header, and it succeded!

**Comment by Remco123** [comment]
Does everything then work as expected? Like it successfully boots to the desktop?

**Comment by asiawin** [comment]
> Does everything then work as expected? Like it successfully boots to the desktop?

It does boot to desktop and then it page faults

**Comment by Remco123** [comment]
I really advise using the correct compiler for compiling CactusOS. That is probably causing the page-fault.
