### ISSUE TITLE
Can I contribute to this project?

### ISSUE THREAD

**Issue by asiawin** [Remco123/CactusOS#5]
I've found this project a week ago. I've found this project amazing! It's so cool! Maybe I can work on the kernel or the userspace apps?

**Comment by Remco123** [comment]
Thanks for the enthusiasm Asiawin. At the moment I am not really looking for contributors since this is a personal project. Also I only work on this project in my spare time so sometimes I don't do anything for months. I know there are some projects out there who do search for contributors so I would ask them instead. Hope this helps and please know that this is really appreciated.

**Comment by asiawin** [comment]
So that means you are sometimes free? Then can you contribute to my [CadexOS](https://github.com/CadexOS/Cadex-OS-Official) project? It's written in C and some apps for it are written in C++. Can you help me with my mouse driver? It's full of bugs and I can't seem to figure out why it happens.

**Comment by Remco123** [comment]
Quite the opposite actually, I only work on CactusOS when I have the time and sometimes I am very busy. I can see if I can fix your mouse driver but I am not going to contribute to your OS. Have you posted your issue on the osdev forum by any chance?

**Comment by asiawin** [comment]
> Quite the opposite actually, I only work on CactusOS when I have the time and sometimes I am very busy. I can see if I can fix your mouse driver but I am not going to contribute to your OS. Have you posted your issue on the osdev forum by any chance?

I can't find any resources related to mouse driver. Can you just help me with the mouse driver?I just need that and everything else I know.
