### ISSUE TITLE
Boot partition not found

### ISSUE THREAD

**Issue by hello01-debug** [Remco123/CactusOS#8]
I have an i686-elf cross-compiler. I built the OS with make and ran it with ```make qemu``` but it claimed the boot partition wasn't present. Can you tell me what I'm doing wrong?

**Comment by hello01-debug** [comment]
It seems to be trying to boot off of the blank image file I attached, as it searches the QEMU HARDDISK for a boot signature, then complains because it can't find it. It then says it can't open B:\\debug.sym because it doesn't exist. Please help!

**Comment by Remco123** [comment]
Can you try booting the iso with the following command in the terminal? 
`qemu-system-i386 -cdrom CactusOS.iso -serial stdio -boot d -device VGA,edid=on,xres=1024,yres=768 `
It is probably giving a error since it is trying to include a image file that does not exist, the master branch is still a development version so it does not always work as intended. Hope this helps!

**Comment by zmmaj** [comment]
Hm... I have same problem... After grub menu I got 
Error: Boot partition not found/present
I was compile OS via make CactusOS.iso
AND.. I haven't support for edid. but that is minor problem. Bigger problem is that I can not start OS from qemu.last is
[798]  (Error) Boot partition is not found/present
Got page Fault  etc.. see picture below
![Screenshot from 2022-09-21 20-58-40](https://user-images.githubusercontent.com/8336904/191590008-240a95f7-dd20-4568-ac20-4ef2ae8c802f.png)
